quintilesims/layer0

api/backend/ecs/environment_manager.go
api/backend/ecs/load_balancer_manager.go
api/backend/ecs/service_manager.go
cli/printer/text.go
common/aws/ecs/ecs.go
common/waitutils/waiter.go
runner/Makefile
runner/job/environment.go
runner/job/loadbalancer.go
runner/job/service.go

This calls `ecs.StopTask` on each task a service is running before deleting the service. This also removes the `waitUntilServiceStopped` function, as it appears ecs no longer requires the number of running tasks to be 0 before being able to call `ecs.DeleteService`. I've also bumped up the wait times for jobs, as I noticed relatively small environments are bumping up to about 60% of max allowed time. 
Iv'e tested this against an environment with a large number of services running (10), but this still needs to be QA'd against a service that doesn't respond to kill commands before merging. 
This fixes https://github.com/quintilesims/layer0/issues/34 and https://github.com/quintilesims/layer0/issues/10

Force service delete

---

docs-src/material/drawer.html

The download link now points to [docs_site]/#download.
Closes #50

Fix download link in drawer

---

tests/smoke/service.bats

Addresses (#72)
It was necessary to explicitly target the latest deploy in the affected tests.

Target latest deploy explicitly

---

api/backend/ecs/cluster_scaler.go

Noticed an issue where if the task definition specifies `memoryReservation` instead of `memory`, the `Memory` field on the `ecs.TaskDefinition` is nil. This fix safely checks the memory fields and calculates based on whichever field is present.

check for memory reservation and memory in cluster scaler

---

setup/context/commands.go

Running the command outputs the following bash script suggestion 
```
```
which is invalid in a windows environment. Updated the code to take into account the operating system at runtime, to make an exception for windows and return output that is appropriate for a Powershell user in Windows.
Testing done:
- Confirmed that runtime checking of the flag works correctly in MacOS. 
- Confirmed that the command output will work in correctly in Powershell
#150

Updated suggested command output to take into account shell OS

---

api/logic/environment_resource_getter.go

noticed the environment scaler was doing this calculation wrong

recalculate service resource

---

cli/client/environment.go
cli/client/environment_test.go
cli/client/interface.go
cli/client/mock_client/mock_client.go
cli/command/environment_command.go
cli/command/environment_command_test.go
common/models/create_environment_request.go
tests/smoke/environment.bats

#155 Added new --os flag to l0 CLI. --os flag's value maps to the OperatingSystem in the L0 Environment Create model to be consistent with #167.
Testing done:
- Ran unit tests
- Ran system tests with @zpatrick 's help

Added --os flag to l0 cli to allow specifying operating system when creating a new l0 environment

---

api/backend/ecs/task_manager.go
api/backend/ecs/task_manager_test.go
api/backend/interface.go
api/backend/mock_backend/mock_backend.go
api/handlers/task_handler_test.go
api/logic/admin_logic.go
api/logic/job_logic.go
api/logic/task_logic.go
api/logic/task_logic_test.go
cli/client/task.go
cli/client/task_test.go
cli/command/task_command.go
cli/command/task_command_test.go
common/models/create_task_request.go
runner/job/context.go
runner/job/task.go
tests/smoke/task.bats
tests/system/taskPerformance_test.go

After many attempts using ecs's builtin `copy` field, I've determined it's unreliable at best, and most likely broken. I switched over to managing the number of copies by creating them one at a time in the `CreateTask` job. This implementation has worked much more reliably and passes the system test. 
As an added benefit, users are no longer restricted to a maximum of 10 copies in `l0 task create` (which was a limit from ECS). They can now create as many copies as they want. 
closes #159

159 bulk task fix

---

.gitignore
Makefile
cli/Makefile
cli/client/api_client.go
cli/main.go
plugins/Makefile
plugins/terraform/Makefile
plugins/terraform/provider.go
setup/Makefile
tests/system/system_test.go

This also includes standardized makefile conventions for build/release
closes #198

Remove "Basic" prefix from client config

---

common/aws/ecs/ecs.go
tests/system/environmentLink_test.go

Was able to run system tests to verify changes didn't break anything. 
Added some retry logic to env link test since it can sometimes fail if the private service is still coming up. 
closes https://github.com/quintilesims/layer0/issues/197

add binpack strategy to start task/service

---

docs-src/docs/guides/one_off_task.md
docs-src/docs/guides/terraform_beyond_layer0.md
docs-src/mkdocs.yml

Closes #173 & #174 
WIP: Note change to remove the default for table_name in the terraform file. I think having a default here would lead to the `terraform apply` failing due to a DynamoDb Table already existing; especially in a byoo environment where multiple team members could be running through the walkthrough at the same time or fail to clean up deployed resources.
I'm not sure how to style the commands. @tlake did mention that we're moving away from embedding html in the markdown files but I'm not sure what the desired style for commands is?
Also this requires a corresponding change in layer0-examples.

Added new documentation for Terraform beyond Layer0

---

setup/command/endpoint.go
setup/command/endpoint_test.go
setup/instance/outputs.go
setup/module/api/outputs.tf
setup/module/outputs.tf

`l0-setup endpoint -d [name]` now displays `LAYER0_AWS_DYNAMO_TAG_TABLE` and `LAYER0_AWS_DYNAMO_JOB_TABLE` env vars.
Closes #257 
In `layer0/setup/`:
- `command/endpoint.go` (corresponding test in `command/endpoint_test.go`) and `instance/outputs.go` for the changes that display the env vars.
- `module/outputs.tf` and `module/api/outputs.tf` for pulling those vars out from the module as outputs.
1. Update module source
- Run `l0-setup init [name]`; when prompted for "Source:", enter the full path to `.../layer0/setup/module`
2. Populate .tfstate
- Run `l0-setup apply [name]`
3. Confirm that dynamo env vars are displayed
- Run `l0-setup endpoint -d [name]`

Display dynamodb variables for 'endpoint -d'

---

api/backend/ecs/utilities.go
api/logic/job_logic.go
common/aws/cloudwatchlogs/cloudwatchlogs.go

* Removes debug statements
* Limits number of streams to 1000. This takes between 2-4 seconds for a `l0 service logs` call. Seems a reasonable stream:time ratio to me - open to suggestions if it should be changed. 
* Fixed broken exit login on pagination function

limit streams to 1000/call

---

api/backend/ecs/utilities.go
api/backend/ecs/utilities_test.go
api/logic/job_logic.go
common/aws/cloudwatchlogs/cloudwatchlogs.go

Fixes a regression which caused `l0 task/service logs` command to return empty results. This regression was introduced by #241.
Create a l0 task or service that generates logs. For example, you can follow the [one-off-task guide](http://layer0.ims.io/guides/one_off_task/). Once the task is created, use `l0 task logs <taskid>` to confirm that the logs written are correctly being output as they are being written to cloudwatch logs.
The logs visible from the Cloudwatch logs sections in AWS console, should match the output generated by `l0 task logs <taskid>`.
**Checklist**
closes #259

Removed storedBytes check

---

setup/module/api/outputs.tf

Updates instances of `${aws_dynamo_table...}` in `setup/module/api/outputs.tf` with `${aws_dynamodb_table...}`.
1. Clone; `make build` l0-setup
2. `l0-setup init [name]`
3. `l0-setup apply [name]`
**Checklist**
closes #278

fix bad 'aws_dynamo_table' var name

---

plugins/terraform/data_source_layer0_api.go
plugins/terraform/data_source_layer0_deploy.go
plugins/terraform/data_source_layer0_deploy_test.go
plugins/terraform/data_source_layer0_environment.go
plugins/terraform/data_source_layer0_environment_test.go
plugins/terraform/data_source_layer0_loadbalancer.go
plugins/terraform/data_source_layer0_loadbalancer_test.go
plugins/terraform/data_source_layer0_service.go
plugins/terraform/data_source_layer0_service_test.go
plugins/terraform/data_source_tag_resolver.go
plugins/terraform/provider.go
plugins/terraform/provider_test.go
plugins/terraform/resource_deploy.go
plugins/terraform/resource_deploy_test.go
plugins/terraform/resource_environment_test.go
plugins/terraform/resource_load_balancer_test.go
plugins/terraform/resource_service_test.go

Modifies the Terraform Layer0 provider to add Data Source support for Layer0 created resources. Data Sources added:
- environment
- load balancer
- service
- deploy
Create a terraform file that references existing l0 environment, load balancer, service & deploy. In the output variables, output all the supported variables supported for a given resource. Execute `terraform apply` and check the output.
For example:
```
provider "layer0" {
endpoint        = "${var.endpoint}"
token             = "${var.token}"
skip_ssl_verify = true
}
data "layer0_deploy" "service-a-dpl" {
name    = "some-cool-service-dpl"
version = "1"
}
output "deploy" {
value = "${data.layer0_deploy.service-a-dpl.id}"
}
```
**Checklist**
closes #263

Added data sources: environment, loadbalancer, service & deploy

---

plugins/terraform/data_source_layer0_loadbalancer.go
plugins/terraform/data_source_layer0_service.go
plugins/terraform/resource_deploy.go
plugins/terraform/resource_environment.go
tests/system/cases/datasources/Dockerrun.aws.json
tests/system/cases/datasources/main.tf
tests/system/cases/datasources/outputs.tf
tests/system/cases/datasources/variables.tf
tests/system/cases/modules/sts/outputs.tf
tests/system/datasources_test.go

Adds systems tests to verify the output of Layer0 provider's Datasource entities added in #263 . Also fixes functionality that exposes `layer0_deploy.version` & `enviornment.cluster_count` resources.
From the `./tests/system` directory run `go test -v -debug -run TestDataSources`.
**Checklist**
closes #280

Issue 280 datasource system tests

---

setup/docker/config.go
setup/docker/utils.go
setup/instance/init.go

Warns the user when running `l0-setup init` if the following is cases are met:
- if the auth property in the docker config file is empty
- if the docker config file is using a credential store
The warning message informs the user about the issue and suggests a potential solution.
Run l0-setup init with the docker config:
**Case 1: Missing Auth information**
```
{
"auths": {}
}
```
**Case 2: Using a credential store**
```
{
"auths": {
"private-docker-repository.io": {}
},
"credsStore": "osxkeychain"
}
```
**Checklist**
closes #255

Warn user if the docker config files doesn't contain expected information

---

tests/smoke/deploy.bats
tests/smoke/load_balancer.bats
tests/smoke/service.bats
tests/smoke/task.bats

Fixes smoke tests that were failing on service create commands due to deploy version or deploy:latest no being explicitly specified.
**Checklist**

Fixed smoketests - service create needs deploy_name:latest

---

api/backend/ecs/deploy_manager.go
api/backend/ecs/environment_manager.go
api/backend/ecs/load_balancer_manager.go
api/backend/ecs/service_manager.go
api/logic/service_logic.go
cli/client/api_client.go
cli/client/api_client_test.go
cli/client/errors.go
common/errors/code.go
plugins/terraform/resource_layer0_deploy.go
plugins/terraform/resource_layer0_environment.go
plugins/terraform/resource_layer0_load_balancer.go
plugins/terraform/resource_layer0_service.go

API returns `<Entity>DoesNotExist` error code when GET requests are made on an entity that does not exist. This is captured more explicitly in the Terraform plugin, allowing Terraform to gracefully handle when entities don't exist. 
1. Create entities using Terraform
2. Delete the entities outside of Terraform (e.g. the CLI)
3. Run `terraform plan`; it should show that the deleted entities are marked for re-creation.   
closes #113

Consistently catch <Entity> does not exist errors

---

api/backend/ecs/task_manager.go
api/handlers/errors.go
api/logic/task_logic.go
common/db/job_store/dynamo.go

Return 404 Http response when a resource is not found:
- Deploy
- Service
- Environment
- Job
- Load Balancer
- Task
Run API locally. Test the below endpoints with a random id value that doesn't exist. Confirm you receive a 404 rather than a 500.
1. GET, DELETE entity/{id} for deploy, service, environment, job, load balancer & task
2. PUT service/{id}/scale & service/{id}/deploy
3. GET service/{id}/logs & task/{id}/logs 
**Checklist**
closes #304

Return '404 Not Found' errors when resource not found

---

api/logic/tag_janitor.go
api/logic/tag_janitor_test.go
api/main.go
cli/command/task_command.go
cli/command/task_command_test.go

Addresses the situation where the dynamodb task ends up with leftover tags which don't correspond to a ecs task. This causes the l0 cli to return errors when when executing commands like `l0 task get \*`. This PR addresses the CLI and the leftover Tags in 2 parts:
**CLI:**
Return a debug message when iterating over tasks and a task is not found.
**API:**
Add a new Tags Janitor that searches for and deletes leftover tags as result of ECS Tasks being removed, every 10 minutes.
---
Unit Test: `go test`
You can also simulate the left over task tag with the following steps:
1. Create a one off task in layer0
2. Ensure a corresponding tag exists in the dynamo db table l0_<l0_prefix>_tags table
3. Duplicate the corresponding tag …

Add leftover tags janitor and handle resolving leftover tags in CLI.

---

setup/instance/upgrade.go

…er compliant (#310)
If the current version of a user's layer0 (as defined in ~/.layer0/<instance>/main.tf.json)
is not semver compatible, this change will notify the user that they can use the --force
flag to override the message.
Include a short summary of what this PR intends to fix and/or a reference to an existing issue.
Issue #310 
Changes console output when `l0-setup upgrade <instance_name> <version>` is run if the layer0 instance's version is not semver compatible. User will be directed to use `--force` to override the behavior.
Include steps to test intended functionality.
Use a non-standard version for your layer0, e.g. in ~/.layer0/<instance>/main.tf.json, set the version field to something like latest, e.g. …

WIP: l0-setup upgrade: Breadcrumb message when current version is not SemV

---

api/main.go
api/provider/aws/common.go
api/provider/aws/environment_list.go
api/provider/aws/load_balancer_update.go
api/provider/aws/task.go
api/provider/aws/task_create.go
api/provider/aws/task_delete.go
api/provider/aws/task_list.go
api/provider/aws/task_list_test.go
api/provider/aws/task_read.go
api/provider/mock_provider/mock_deploy.go

List() returns a slice of models.TaskSummary objects which describe the Task and the Environment it is contained in
Task entity CRUD methods will be split into separate files rather than one big file
listClusterNames() now in common.go since it is also used by Environment List
List Provider now includes the config.APIConfig object in the constructor
Unit test for populating Task Summaries
Include steps to test intended functionality.
**Checklist**
Work is going toward #274

274: Task List provider/aws implementation

---

setup/instance/init.go
setup/terraform/terraform.go

This adds the "terraform init" to the l0-setup.
Clone branch, cd to layer0/setup and run `go run main.go init <instance name>`
You should see the terraform success message then
**Checklist**
**Concerns**
- I've removed the color in the output, but I'm wondering if this should be muted too since it's confusing that it tells the user they can run terraform plan.
- No download indicator when running the `terraform get` command
closes #
#338

Added terraform init to l0-setup init

---

api/provider/aws/deploy_read.go
api/provider/aws/deploy_read_test.go

The newDeployModel() constructor will take the deployID passed to Read() and then populate
the model with as much information as can be provided by the tags db before making the API call
to AWS
Note that Deploy List() has a different workflow that won't use the stated SummaryModel constructor pattern because AWS gives back TaskDefinition ARNs. So the helper function will take the ARNs given by AWS to populate the Summary.
Unit test
**Checklist**

Make Deploy Read() use new Model constructor pattern

---

api/controllers/swagger.go
api/provider/aws/README.md
api/provider/aws/common.go
api/provider/aws/common_test.go
api/provider/aws/service_list.go
api/provider/aws/service_read.go
api/provider/aws/service_read_test.go
common/models/deployment.go
common/models/service.go

Adds the `Read` operation to the Service Provider.
- Unit tests
- Run API locally
- confirm compilation
- hit http://localhost:9090/api/?url=/swagger.json with a browser to confirm Swagger functionality
**Checklist**
- ~Smoke tests (if applicable)~
- ~System tests (if applicable)~
- ~Documentation (if applicable)~
-----
Apologies for the difficulty in reviewing this PR; the subject matter is both the current changes as well as a post-merge review of Seshi's work. You might not need to look at all of them, but in an attempt to ease this headache, the files immediately relevant to `Service Provider: Read()` are these:
```
common/models/
- deployment.go
- service.go
api/controllers/
- service.go
- service_test.go
- swagger.go …
```

274: Service provider: Read

---

api/provider/aws/service_read.go

Fixes a bug where `readService()` was called using a not-fully-qualified `serviceID`.
This is tricky to do with things in flight, since at this point in time the creation of a `deploy` doesn't create an `arn` tag in the tag database given the work currently in `api-refactor` (this work _does_ exist in the `deploy` work that Brandon and Josh have been working on, but at the time of this writing, those changes haven't been merged into `api-refactor` yet).
My current workaround is hacky af and as follows:
1. Get the ID of an existing service with `l0 service list` using Layer0 v0.10.3 or similar
2. Find the Task Definition's ARN
- In `service_read.go:Read()` around line 29, look for where `taskDefinitionARN` gets defined and …

274: Service Provider: Read: Bugfix

---

api/provider/aws/task_list.go

It seems that part of `task_list.go` got messed up in a merge somewhere; most apparent, `makeTaskSummaryModels()` had been overwritten with an outdated `populateSummariesFromTaskARNs()`. This is an attempt to fix it. WARNING: I'm not particularly familiar with this part of the codebase, so it's very possible that I've overlooked something; but the tests pass now, which they don't currently do in `api-refactor`.
- `cd layer0/api && go test ./...`
- Confirm if desired behavior is intact
- Make sure that everything looks right
**Checklist**
closes #
(reference the issue(s) this pull request closes)

Repair 'task_list.go'

---

api/controllers/deploy_test.go
api/provider/aws/deploy_list.go
api/provider/aws/task_list.go
api/provider/mock_provider/mock_deploy.go
api/provider/mock_provider/mock_environment.go
api/provider/mock_provider/mock_loadbalancer.go
api/provider/mock_provider/mock_service.go
api/provider/mock_provider/mock_task.go

Deploy List() will now explicitly only return active Task Definitions and Task Definition Families.
Manually test Deploy methods with Swagger
Unit tests
**Checklist**

Deploy Provider: List only Active Task Definitions

---

api/provider/aws/deploy_create.go
api/provider/aws/deploy_create_test.go
api/provider/aws/environment_create.go
api/provider/aws/job_runner.go
api/provider/aws/load_balancer_create.go
api/provider/aws/service_create.go
api/provider/deploy.go
api/provider/environment.go
api/provider/load_balancer.go
api/provider/mock_provider/mock_deploy.go
api/provider/mock_provider/mock_environment.go
api/provider/mock_provider/mock_loadbalancer.go
api/provider/mock_provider/mock_service.go
api/provider/mock_provider/mock_task.go
api/provider/service.go
api/provider/task.go

This removes the `entity.Read` calls at the end of `entity.Create` functions.
I encountered a bug where `entity.Create` would complete fine, but `entity.Read` would return an error. This would cause the retry logic in the job runner to execute unnecessarily. 
I also did some cleanup for `deploy.Create`
Unit tests
**Checklist**

Return entityID on entity.Create

---

client/mock_client/mock_client.go
client/tag.go
client/tag_test.go

Change the target of the GET call for Tags to /tag.
Manually test entity operations that use the resolveSingleEntityIDHelper function and ensure that the API properly processes the call.
**Checklist**
closes #392

Tag API Client fix to target /tag of the API

---

api/provider/aws/job_runner.go

Returns Entity ID strings from updateEntity functions. This fixes a bug where update operations in the `command` package receive an empty string for `job.Result`, resulting in a marshalling error when trying to read an entity after the update operation (successfully) finishes.
Confirm that update operations no longer fail for environments, loadbalancers, and services.

Return 'req.EntityID' strings from 'updateEntity' funcs

---

cli/command/base.go

Fixes a bug in `waitOnJobHelper()` where `nil` was returned instead of `err` and changes the name of `onCompleteFn` to `onCompleteFN`.
Make sure those changes are in there.

Fix error-handling bug and slight naming nit

---

cli/command/test_helpers.go

Includes the former `testutils` function `getCLIContext`, which is used for unit testing `command`

add GetCLIContext func

---

api/controllers/tag_test.go
api/provider/aws/defaults.go
api/provider/aws/environment_create.go
common/models/create_environment_request.go

Allows clients to specify an empty os field for environment create. The 'linux' option will be used by default. 
manually
**Checklist**

Allow empty os field in environment create

---

api/provider/aws/load_balancer_create_test.go

Because RenderLoadBalancerRolePolicy was recently changed as an
exportable function, the capitalization change causes the LB Create
test to fail.
`go test` in the `api/provider/aws` directory. This is currently failing in the current state of the `api-refactor` branch.
**Checklist**

Fix aws provider unit test on RenderLoadBalancerRolPolicy helper function

---

setup/module/api/variables.tf

Updates the default Linux AMI used for Layer0.
Cannot be properly tested until l0-setup has been refactored. Merging is a "risk" as-is.

[l0-setup] update linux AMI

---

setup/module/api/policies/ecs_role_policy.json

Adds an ECS role to our default Layer0 policy that enables CloudWatch Metrics for ECS Clusters.
Tested on v0.10.3, confirmed that metrics appeared for Consul and HelloWorld apps. 
closes #
https://github.com/quintilesims/layer0/issues/431

Add telemetry role to default IAM/ECS policy

---

tests/system/import_test.go

After a recent merge, some things broke in the import system test. These changes should resolve those breaks.
`go test ./... -v -dry` should compile. Note the tests will not succeed as that is for a future PR.
**Checklist**

MAINT: Fix import system test after merge of env max scale changes

---

api/main.go
api/provider/aws/admin.go
api/provider/aws/common.go
api/provider/aws/service_delete.go
api/provider/aws/service_logs.go
api/provider/aws/service_read.go
api/provider/aws/test_aws/admin_init_test.go

Adds an `AdminProvider` object to the `provider/aws` package. 
This object has an `Init()` function that will add all of the necessary tags for the API entities. 
* Unit tests
* Manually remove all api-related tags from the Dynamo table, run the api locally, and the tags should get re-populated. All `l0 entity get` commands should succeed for `api` entities. 
**Checklist**

Create API tags on startup

---

setup/instance/inputs.go
setup/module/main.tf
setup/module/vpc/main.tf
setup/module/vpc/variables.tf

Updates the API's VPC module to rely on Availability data source rather than hardcoded values of a,b & c. This allows a layer0 instance to be created in any regions that don't have the expected AZs.
Create a new Layer0 Instance for a region that has more/less than the standard a, b & c zones like `us-west-1`. The creation via l0-setup should succeed. 
**Checklist**
closes #452

Use AWS AZ data source when creating Layer0 API subnets

---

setup/module/api/Dockerrun.aws.json
setup/module/api/core.tf
setup/module/main.tf
setup/module/vpc/main.tf

terraform fmt was also run to correct formatting issues for the module
Fixes an issue where the l0 api service's task will not run because of a missing ssh key variable.
Create a new l0 instance with `l0-setup` and upload a docker image through `flow.sh api` and make sure your new l0 instance uses that version. Make sure the task definition runs and starts without issue.
**Checklist**
closes #455

455: Add ssh key pair variable to l0 api task definition

---

api/controllers/admin.go
api/controllers/health.go
api/main.go
setup/instance/apply.go
setup/module/api/load_balancer.tf

The admin endpoint /admin/health should not require basic auth.
The way the fireball controller is coded, even if the ELB health check ping target is changed to TCP:port, the controller will still return an HTTP 401 response. 
This change removes /admin/health and instead creates a new endpoint, /health that will not require basic auth.
Create a new layer0 instance (as of this writing, include the fix in issue #455). When `l0-setup apply` is run, the instance should come up healthy and the apply should finish without issue.
**Checklist**
closes #456

456: Allow the Layer0 API Health check to not require basic auth

---

setup/module/api/policies/ecs_role_policy.json

Adds Cloudwatch metrics to default IAM ecs role.
Tested manually via l0-setup and a new cluster creation; verified that ECS metrics became populated for a given cluster. 
closes #
https://github.com/quintilesims/layer0/issues/464

enable ecs metrics via IAM policy

---

api/backend/ecs/resource_manager.go
api/backend/ecs/resource_manager_test.go

Removes a check for the ECS agent being connected when gathering resource providers; an instance should still be considered to exist even when the agent happens to be disconnected.
Run unit tests. Manually perform and monitor scaling operations.
**Checklist**
closes #461

[v0.10.4] scaler patch

---

common/config/config.go

The previous PR #476 was supposed to remove this line, as we are not recognizing a default AWS region any longer.
**Checklist**

MAINT: Remove default AWS region from config

---

common/aws/ecs/ecs.go

The methods called in the AWS SDK that pull back Task Definitions should only be retrieving Task Definitions that are active. Without filtering Task Definitions by status, inactive Task Definitions can still be retrieved. For Layer0 instances that have been up for a long time, inactive Task Definitions can accumulate and has been known to slow the operation `l0 deploy list` down considerably.
Running `l0 deploy list` operations (both with and without the `--all` flag)
**Checklist**

MAINT: Make l0 deploy list only return active task definitions

---

setup/command/apply.go
setup/command/aws.go
setup/command/list.go
setup/command/pull.go
setup/command/push.go

When a new AWS Provider needs to be created or an AWS session needs to be established, aws.Config needs to contain the correct region for interactions with AWS to work.
In the case where l0 instances are initialized and set up in a region other than the default us-west-2, the resources will create in the region specified in the init wizard, but pushing terraform state to the S3 bucket fails because it was always assumed that the AWS region would be us-west-2.
To fix this, anytime an AWS Provider is needed, the instance derives what region it's in (assuming that l0-setup apply ran to completion), and then passes that region into the AWS Provider helper function so that aws.Config sets the correct region for API operations via the WithRegion() method.
The …

444: Fix l0-setup apply issue for instances created in another region

---

api/backend/ecs/environment_manager.go
tests/smoke/admin.bats

Updates the Windows ECS Agent to the latest version as specified in the canonical Windows ECS script https://github.com/aws/amazon-ecs-agent/blob/master/misc/windows-deploy/user-data.ps1#L7:17
Also removes a test target from our smoketests.
Create a Windows environment with `-os windows` and a sample windows service.
**Checklist**

update windows ECS agent version

---

docs-src/docs/setup/destroy.md
docs-src/docs/setup/install.md
docs-src/docs/setup/upgrade.md

The files in `docs-src/docs/setup/` still had some code blocks with leading `$` characters, which made copying and pasting more trouble than it should be.

Remove leading '$' in code blocks to improve copypaste

---

setup/instance/inputs.go

Adds AZ overlap stipulation to `vpc_id` input variable for `l0-setup`. 
closes #496

add overlapping az stipulation to vpc_id input

---

scripts/flow.sh

Changes `scripts/flow.sh` to fix an issue where the environments are not deleted due to a CLI syntax change made for `l0 environment delete`.
The --wait flag has been removed from l0 environment delete, and each of the iterations of the environments to delete should not be sent to the background.
Create a few environments and deploys and then run `flow.sh delete`. Confirm that everything except for the api environment and deploy are deleted.
**Checklist**
closes #510

510: Modify flow.sh to fix the delete environment stage

---

scripts/flow.sh

Fixes `flow.sh delete` so that it doesn't delete the layer0 api's deploy.
`flow.sh delete` on an existing layer0 instance you can destroy. Confirm that the layer0 api deploy is not deleted `l0 deploy list`
**Checklist**
closes #517

517: Fix flow.sh to not delete api deploy

---

api/backend/ecs/load_balancer_manager.go

It sets a CertificateARN property on a port as well as the CertificateName. The TF Provider will use the ARN to populate its `certificate` property in the schema. 
Use the sample terraform config below
```
resource "layer0_environment" "env_a" {
name = "a"
}
resource "layer0_load_balancer" "haproxy" {
name        = "test-lb"
environment = "${layer0_environment.env_a.id}"
private     = false
port {
host_port      = 443
container_port = 80
protocol       = "https"
certificate    = "<redacted>"
}
}
```
Apply the changes using `terraform apply`
Confirm that a consecutive apply won't detect any changes and try to recreate any resources.
**Checklist**
- ~[ ] System tests (if …

Set the LoadBalancer's port's CertificateARN 

---

setup/command/endpoint.go
setup/command/endpoint_test.go
setup/instance/inputs.go
setup/instance/outputs.go

Adds region to the outputs for -d flag
**Checklist**
closes #541

541: Add AWS region output to -d flag for endpoint and allow spaces for inputs

---

api/provider/aws/common.go
api/provider/aws/load_balancer_create.go
api/provider/aws/load_balancer_read.go
api/provider/aws/load_balancer_update.go
api/provider/aws/test_aws/environment_create_test.go
api/provider/aws/test_aws/load_balancer_create_test.go
api/provider/aws/test_aws/load_balancer_read_test.go
api/provider/aws/test_aws/load_balancer_update_test.go
cli/command/load_balancer.go
cli/command/load_balancer_test.go
cli/printer/interface.go
cli/printer/json.go
cli/printer/test.go
cli/printer/text.go
cli/printer/text_test.go
common/errors/code.go
common/models/create_load_balancer_request.go
common/models/load_balancer.go
common/models/update_load_balancer_request.go
common/models/validation_test.go
docs-src/docs/reference/cli.md
docs-src/docs/reference/terraform-plugin.md
plugins/terraform/layer0/resource_layer0_load_balancer.go
plugins/terraform/layer0/resource_layer0_load_balancer_test.go

This adds idle timeout support for load balancers to the api-refactor branches.
* Adds an optional flag for `l0 loadbalancer create`, `--idle-timeout` to specify the idle timeout of the load balancer at creation time
* Adds loadbalancer subcommand `l0 loadbalancer idletimeout` which allows the user to specify the idle timeout of a given load balancer
* Adds terraform support for idle timeout by adding a new key to the load balancer resource `idle_timeout`
Unit tests have been added/modified.
Note: Other unit tests have been modified that are currently breaking in api-refactor.
Manually via the CLI: `l0 loadbalancer create env_a lb_a --idle-timeout 100` and then `l0 loadbalancer idletimeout lb_a 200`
Via terraform:
``` …
```

559: Add load balancer idle timeout support for api-refactor

---

api/provider/aws/defaults.go
setup/module/api/user_data.sh

Modifies the L0 API module to send ECS agent, Docker, and other Linux system logs to the CloudWatch log group created when the instance is created.
Create a new instance with `l0-setup` and note the new log streams created in the log group of your instance.
**Checklist**
closes #424

424: Add support for sending L0 api logs to cloudwatch

---

setup/module/api/user_data.sh

This PR resolves an issue in the `api-refactor` (and children branches) with the ECS container's user data script where the Layer0 API service's EC2 instances would not register with the ECS cluster created for the API service.
Create a new layer0 instance through `l0-setup`. `l0-setup` must complete without failure. The API service's EC2 instances should register correctly with the ECS cluster and the service's task should run without issue. Confirm that the EC2 instances are registering correctly by reviewing the `ECS Instances` tab for the cluster called `l0-<prefix>` where prefix is the name of the layer0 instance specified at `l0-setup` time.
**Checklist**
~- [ ] …

577: api-refactor, Fix for issue preventing L0 API instances from registering to ECS cluster

---

api/provider/aws/service_create.go
api/provider/aws/test_aws/service_create_test.go
common/errors/code.go

Include a short summary of what this PR intends to fix and/or a reference to an existing issue.
Normally I would say smoketests. However, since `api-refactor` is in a bad state, I just wrote a tiny bash script that calls `l0 loadbalancer create ...` immediately followed by `l0 service create --loadbalancer ...`. The little-to-no delay between the requests should cause the eventual consistency issue to appear, and we should see the api gracefully handle + retry when that occurs. 
Here is an excerpt of my api logs when this happened:
```
2018/03/27 13:01:25 POST /service
2018/03/27 13:01:26 [DEBUG] Failed service create, will retry (InvalidParameterException: Unable to assume role and validate the listeners configured on …
```

Retry service create

---

api/provider/aws/common.go
api/provider/aws/load_balancer_delete.go
api/provider/aws/test_aws/load_balancer_delete_test.go

Adds retry logic to lb-delete to handle eventual consistency errors.
- Retry on loadbalancer describe to verify delete
- Retry on security groups list to verify delete
**Checklist**
closes #584

Add retry logic for lb delete

---

api/provider/aws/admin_logs.go
docs-src/docs/reference/cli.md

Closes issue #594 
- Implements a change to the pattern filter that is used for the command `l0 admin logs` to capture more events from the CloudWatch log stream that CloudTrail uses when a Layer0 instance is created.
- Docmentation cleanup: added usage patterns for the commands `l0 admin logs` and `l0 environment logs`
How to test:
Create a new Layer0 instance through `l0-setup`. Execute commands that will create CloudTrail events that were not being captured before (any creates such as CreateService, CreateLoadBalancer, etc will suffice). These CloudTrail events will be keyed on userIdentity.userName = l0-fqdn-user where fqdn is the name of your Layer0 instance.

594: Fix filter pattern for l0 admin logs to capture more events

---

api/provider/aws/common.go
tests/smoke/common/test_helpers.bash
tests/smoke/service.bats
tests/smoke/task.bats

Updates Test smoke tests to use helper method so that tasks are created after the cluster has the capacity to create tasks
Run the following commands:
`bats tasks.bats`
`bats service.bats`
**Checklist**
fixes #602

- added helper method to smoke tests to wait for env scale

---

setup/module/api/core.tf

Updates latest terraform resource lookup to use most recent `name` values for linux, Windows AMIs. 
**Checklist**
closes #
https://github.com/quintilesims/layer0/issues/607

update to latest AMI

---

api/main.go
common/aws/provider/connection.go
runner/main.go

`layer0/common/aws/provider/connection.go` contained code for a ticker intended to provide a rate limit for the `l0-api`. However, this resulted in infinitely-growing CPU usage on the AWS instance because:
- A new ticker would be created every time `connection.go::getConfig()` was called
- Using `time.Tick()` instead of `time.NewTicker()` yielded only the ticker - it did not yield a mechanism by which to terminate the ticker.
This PR replaces `time.Tick()` with `time.NewTicker()` in order to obtain the mechanism by which a ticker can be stopped. The ticker - henceforth referred to as the rate limiter - is initialized with a default `time.Duration` value, and control of the rate limiter is passed to outside packages by way of public functions. `api/main.go` and `runner/main.go` now handle …

Fix CPU leak caused by `time.Tick`

---

docs-src/docs/reference/terraform-plugin.md

`~/.terraform.d/plugins` rather than arbitrary install directory
Update the docs page to help better with the terraform plugin installation.
Try the instructions now :)
**Checklist**
closes #
No related issue.

use home dir for terraform plugin

---

setup/module/main.tf

The AWS 2.0+ providers are not compatible with Layer0's `l0-setup`. This change caps the provider at pre-2.0 versions.
Run `l0-setup` to completion. There should be no terraform validation errors.
**Checklist**
N/A on all
closes #
https://github.com/quintilesims/layer0/issues/632

Capping AWS provider to pre-2.0 versions

---

common/aws/ecs/ecs.go
setup/module/api/core.tf

Include a fix to OCEMCM-9665, update the new ARN format of ECS services

ecs service ARN update ,fixed OCEMCM-9665.

---

Makefile
api/logic/job_logic.go
common/config/config.go
setup/command/init.go
setup/instance/inputs.go
setup/module/api/Dockerrun.aws.json
setup/module/api/deploy.tf
setup/module/api/variables.tf
setup/module/main.tf
setup/module/variables.tf

Introduce an optional docker-registry configuration for layer0-api, where a custom registry could be configured during the deploy, which will be used to pull the layer0 images. (dockerhub is used as the default docker registry location)
Layer0-api is running OK (using both default and custom docker-registry)
Layer0-jobs are pulling the container images from the intended docker-registry

OCEMCM-11036

---

.travis.yml
DEVELOP.md
api/backend/ecs/environment_manager.go
api/backend/ecs/environment_manager_test.go
setup/module/api/core.tf
setup/module/api/environment.tf

1: Updated the layer0 ec2 image to Linux2 latest version as suggested by aws
2: Update the root size from 8gb to 30gb
3: Updated the default image from t2 to t3.
4: Added the gitlab pipeline trigger for image sync to d.ims.io
5: Removed the second drive used be deployed in the default settings in old Image.

Ocemcm 11302 single drive
