api/handlers/deploy_handler.go, api/handlers/load_balancer_handler.go, api/handlers/service_handler.go, cli/client/deploy.go, cli/client/deploy_test.go, cli/client/load_balancer.go, cli/client/load_balancer_test.go, cli/client/service.go, cli/client/service_test.go
=> Make urls consistent

api/backend/ecs/id/id.go, api/backend/ecs/service_manager.go, api/backend/ecs/service_manager_test.go, api/handlers/service_handler_test.go, api/logic/mock_logic/mock_service_logic.go, api/logic/service_logic.go, cli/client/interface.go, cli/client/mock_client/mock_client.go, cli/client/service.go, cli/client/service_test.go, cli/command/service_command.go, cli/command/service_command_test.go, cli/printer/interface.go, cli/printer/json.go, cli/printer/test.go, cli/printer/text.go, common/aws/ecs/ecs.go, common/aws/ecs/ecs_provider_decorator.go, common/aws/ecs/mock_ecs/mock_ecs.go
Improves performance in the API, prints the summary model in the CLI
=> Bulk List for Services

api/backend/ecs/load_balancer_manager.go, api/handlers/load_balancer_handler_test.go, api/logic/load_balancer_logic.go, api/logic/load_balancer_logic_test.go, api/logic/mock_logic/mock_load_balancer_logic.go, cli/client/interface.go, cli/client/load_balancer.go, cli/client/load_balancer_test.go, cli/client/mock_client/mock_client.go, cli/command/load_balancer_command.go, cli/command/load_balancer_command_test.go, cli/printer/interface.go, cli/printer/json.go, cli/printer/test.go, cli/printer/text.go, scripts/Makefile.mocks
Improves performance in the API, prints the summary model in the CLI
=> Bulk List for Load Balancers

api/backend/ecs/cluster_scaler.go, api/backend/ecs/task_manager.go, api/handlers/task_handler_test.go, api/logic/mock_logic/mock_task_logic.go, api/logic/task_logic.go, cli/client/interface.go, cli/client/mock_client/mock_client.go, cli/client/task.go, cli/client/task_test.go, cli/command/task_command.go, cli/command/task_command_test.go, cli/printer/interface.go, cli/printer/json.go, cli/printer/test.go, cli/printer/text.go
Improves performance in the API, prints the summary model in the CLI
=> Bulk List for Tasks

docs/docs/reference/terraform-plugin.md
Revise languange and note that Terraform binary is included with
Layer0 release.
=> Update Docs for Terraform Provider (#45)

setup/context/commands.go, setup/context/context.go
=> dockercfg now included for backup/restore

.gitignore, docs-src/docs/reference/cli.md, docs-src/docs/reference/terraform-plugin.md, plugins/terraform/main.go, plugins/terraform/resource_load_balancer.go
=> Terraform Healthchecks

cli/client/api_client.go, cli/command/error.go
closes https://github.com/quintilesims/layer0/issues/47
=> Add breadcrumb for unset layer0 env variable (#47)

README.md
* Necessary to run main.go from within setup directory
* Need to unset auth token from API shell as well
=> Update README for local API setup

cli/client/api_client.go
closes https://github.com/quintilesims/layer0/issues/79
=> return error on version mismatch

plugins/terraform/resource_load_balancer.go
=> Allow health_check block to be unspecified

setup/context/commands.go, setup/context/context.go, setup/context/docker.go, setup/context/utilities.go, setup/main.go
closes https://github.com/quintilesims/layer0/issues/55
=> Allow config.json and/or dockercfg 

plugins/terraform/resource_load_balancer.go
The plugin now does a proper comparison between the health check object received from `expandHealthCheck` and an empty initialized health check object. If they're equal (i.e. the health check field was completely unspecified in the `layer0.tf` file), the model is populated with our default values.
=> fix for terraform plugin build failure

docs-src/docs/setup/install.md
=> Documentation Typo Fix (#126)

Makefile, plugins/Makefile
=> Integrate Terraform Unit Tests (#177)

CONTRIBUTOR.md
Closes https://github.com/quintilesims/layer0/issues/179
=> add CONTRIBUTOR guidelines

README.md, RELEASE.md
=> Incorporate README Badges (#178)

api/backend/ecs/load_balancer_manager.go, api/backend/ecs/load_balancer_manager_test.go
closes https://github.com/quintilesims/layer0/issues/194
=> remove sg from private lbs

api/logic/environment_logic.go, cli/client/environment.go, cli/client/environment_test.go, cli/client/interface.go, cli/client/mock_client/mock_client.go, cli/command/environment_command.go, cli/command/environment_command_test.go, cli/printer/text.go, cli/printer/text_test.go, tests/smoke/environment.bats
Added support for environment linking in L0 CLI.
Syntax:
`l0 environment link env1 env2`
`l0 environment unlink env1 env2`
=> 186 link env cli

plugins/terraform/provider.go, plugins/terraform/resource_environment_link.go
=> Link environments in Terraform plugin

docs-src/docs/reference/cli.md
closes https://github.com/quintilesims/layer0/issues/187
closes https://github.com/quintilesims/layer0/issues/157
=> CLI docs for environment linking and windows containers

cli/command/environment_command.go, tests/system/Makefile, tests/system/cases/environment_link/main.tf, tests/system/cases/environment_link/outputs.tf, tests/system/clients/layer0_test_client.go, tests/system/environmentLink_test.go
closes https://github.com/quintilesims/layer0/issues/207
=> Environment Link system test

docs-src/docs/reference/cli.md
Closes #142
Additionally, current ongoing work on the guides overhaul will be sure to keep this in mind.
=> Add note to clear up confusion about load balancer ports and health checks

api/logic/job_janitor.go
=> change job lifetime to 1 hour

runner/job/job_test.go, runner/job/runner.go, runner/job/runner_test.go, runner/job/step.go, runner/main.go
* Also removes rollback logic since that is unused
closes #237
=> add retry logic to job load

api/backend/ecs/utilities.go, api/backend/ecs/utilities_test.go, common/aws/cloudwatchlogs/cloudwatchlogs.go, common/aws/cloudwatchlogs/cloudwatchlogs_provider_decorator.go, common/aws/cloudwatchlogs/mock_cloudwatchlogs/mock_cloudwatchlogs.go
Attempting to address several issues:
- empty logs generates error message
- retrieving logs seems slow
=> Task logs refactor

setup/command/endpoint.go, setup/instance/inputs.go, setup/instance/instance.go
closes https://github.com/quintilesims/layer0/issues/242
closes https://github.com/quintilesims/layer0/issues/244
closes https://github.com/quintilesims/layer0/issues/245
=> add endpoint env var helper. add breadcrumb for init error

docs-src/docs/guides/walkthrough/deployment-1.md, docs-src/docs/reference/terraform-plugin.md, docs-src/docs/reference/terraform_introduction.md, docs-src/docs/setup/install.md, docs-src/docs/stylesheets/extra.css, docs-src/mkdocs.yml
Update documentation with information that we've missed or that has caused confusion for users.
No real testing - just read over the documentation changes and see if everything makes sense and is clear. The issue links below should be beneficial in guiding a review.
**Checklist**
- ~Unit tests~
- ~Smoke tests~
- ~System tests~
closes #254
closes #251
=> Fix documentation oversights

api/backend/ecs/deploy_manager.go, api/backend/ecs/deploy_manager_test.go, api/backend/ecs/ecs_test.go, api/backend/ecs/environment_manager_test.go, api/backend/ecs/id/id.go, api/backend/ecs/load_balancer_manager.go, api/backend/ecs/load_balancer_manager_test.go, api/backend/ecs/resource_manager.go, api/backend/ecs/resource_manager_test.go, api/backend/ecs/service_manager.go, api/backend/ecs/service_manager_test.go, api/backend/ecs/task_manager.go, api/backend/ecs/task_manager_test.go, api/backend/ecs/utilities.go, tests/system/Makefile
Fixes InvalidParameterParam issue when running ListTasks. 
I have already ran smoke and system tests. 
**Checklist**
=> remove pending api call from list task

docs-src/docs/reference/terraform-plugin.md
Updates documentation to include information about additional data sources added:
- Deploy
- Environment
- Load Balancer
- Service
Run `mkdocs serve` from the docs-src directory. Navigate to the [Layer0 Terraform Plugin](http://layer0.ims.io/reference/terraform-plugin/) section and confirm the new sections for the datasources mentioned above exist.
**Checklist**
closes #285
=> Updated documentation to include information additional Data Sources

api/provider/aws/deploy_read.go
Deploy `Create()` was changed to insert a new tag, the ARN of the Task Definition created. Deploy `Read()` will use this ARN when invoking the SDK's `DescribeTaskDefinition()` function
Unit tests
**Checklist**
=> Deploy Read() to use TaskDef ARN for DescribeTaskDefinition()

api/provider/aws/deploy_list.go, api/provider/aws/deploy_list_test.go
This will add the implementation of List() for the Deploy provider and include a unit test for the operation
Unit test
**Checklist**
=> 274: Add the implementation of List() for Deploy provider with unit test

api/provider/aws/README.md, api/provider/aws/environment_list.go, api/provider/aws/environment_list_test.go, api/provider/aws/environment_read.go, api/provider/aws/environment_read_test.go, api/provider/aws/load_balancer_list.go, api/provider/aws/load_balancer_list_test.go, api/provider/aws/load_balancer_read.go, api/provider/aws/load_balancer_read_test.go, api/provider/aws/task_list.go, api/provider/aws/task_list_test.go, api/provider/aws/task_read.go, api/provider/aws/task_read_test.go
=> Use 'makeEntityModel' function helpers

.github/PULL_REQUEST_TEMPLATE.md
Add a bit on manual testing in our PR checklist. 
N/A
=> add manual testing to PR checklist

api/scaler/dispatcher.go
This should fix the `fatal error: concurrent map read and map write` error some people have been seeing. 
Run the unit tests in the `scaler` package
**Checklist**
=> add mutex to scaler dispatcher

api/controllers/task.go
Removes a couple of imports that were not used and preventing the binary from compiling.
`go run main.go` in `layer0/api/`
=> Remove extraneous imports

api/controllers/swagger.go, api/job/mock_job/mock_store.go, api/provider/aws/common.go, api/provider/aws/common_test.go, api/provider/aws/deploy_read.go, api/provider/aws/load_balancer_read.go, api/provider/aws/load_balancer_update.go, api/provider/aws/service_create.go, api/provider/aws/service_create_test.go, api/provider/mock_provider/mock_deploy.go, api/provider/mock_provider/mock_environment.go, api/provider/mock_provider/mock_loadbalancer.go, api/provider/mock_provider/mock_service.go, api/provider/mock_provider/mock_task.go, common/models/create_service_request.go
Implements the Create operation for the Service Provider.
- Confirm that the api unit tests pass
- `go test ./...` from `layer0/api/`
- Confirm functionality through Swagger
- `go run main.go` from `layer0/api/`
- Use http://localhost:9090/api/?url=/swagger.json to create a service, both with and without a loadbalancer
- Make sure to convert the contents of a Dockerrun.aws.json file to base64: `openssl base64 -in <infile>`
- Confirm that other service operations function upon services created by this changeset (i.e. can you use Swagger to read a service you've created?)
**Checklist**
closes #
(reference the issue(s) this pull request closes)
=> 274: Service provider: Create

api/main.go, api/provider/mock_provider/mock_deploy.go, api/provider/mock_provider/mock_environment.go, api/provider/mock_provider/mock_loadbalancer.go, api/provider/mock_provider/mock_service.go, api/provider/mock_provider/mock_task.go
=> add max retries to aws config

api/controllers/admin.go, api/controllers/swagger.go, api/main.go, common/config/api.go, common/models/api_config.go
Add admin endpoints to new api-refactor.
May need to add a unit test.go
**Checklist**
closes #
(reference the issue(s) this pull request closes)
=> Add admin endpoints to api and swagger

api/controllers/load_balancer.go, api/controllers/load_balancer_test.go, api/provider/aws/load_balancer_create.go
* Change LB controller verb from Get to Read 
* Fix for the LB Provider Create function when creating private load balancers
This was discovered as part of our testing on the `cli-refactor` branch. I am cherry-picking the changes I had made on the command feature branch into this separate branch, and now basing off of `api-refactor`.
Creating a private load balancer currently does not create the security group for it.
Get->Read paradigm alignment
Manually
**Checklist**
=> API fixes for LoadBalancer controller and provider

api/provider/aws/common.go, api/provider/aws/task_delete.go, api/provider/aws/test_aws/task_create_test.go, api/provider/aws/test_aws/task_delete_test.go, api/provider/aws/test_aws/task_list_test.go, api/provider/aws/test_aws/task_read_test.go
Initial pass at unit test for aws provider.
Include steps to test intended functionality.
**Checklist**
closes #
(reference the issue(s) this pull request closes)
=> Unit test task

api/backend/ecs/load_balancer_manager.go, cli/command/load_balancer_command.go, cli/command/load_balancer_command_test.go, common/models/port.go, docs-src/docs/reference/cli.md, plugins/terraform/resource_layer0_load_balancer.go, plugins/terraform/resource_layer0_load_balancer_test.go
closes #491 
Manually with both terraform and the cli
**Checklist**
=> Allow Certificate ARNs to be used for targeting

api/provider/aws/environment_delete.go, api/provider/aws/test_aws/environment_delete_test.go, common/errors/code.go
This add retry logic got the env delete.
**Checklist**
closes #583
=> Add retry logic for env delete

api/provider/aws/common.go, api/provider/aws/environment_create.go, api/provider/aws/environment_delete.go, api/provider/aws/load_balancer_create.go, api/provider/aws/load_balancer_delete.go, api/provider/aws/load_balancer_update.go, api/provider/aws/test_aws/load_balancer_delete_test.go, api/provider/aws/test_aws/load_balancer_update_test.go, cli/command/load_balancer.go, plugins/terraform/layer0/resource_layer0_environment.go, tests/smoke/load_balancer.bats
Updates smoke tests to test Application & Classic Load Balancers. To get ALB smoke tests to consistently pass, retry logic also had to be introduced around security groups & target groups when creating and deleting load balancers.
Navigate to `./tests/smoke/`
Execute `bats load_balancer.bats`
**Checklist**
Addresses the ALB smoke tests part of #500
=> Application Load Balancer - smoke tests

README.md
* RELEASE_NOTES.md moved in: https://github.com/quintilesims/layer0/commit/d85acd884ff3dd87db916fd84b47137abb82a9e3#diff-781a53e648f3df8d16a08ec083b04bf4
* CONTRIBUTOR.md moved in: https://github.com/quintilesims/layer0/commit/7dcbc28bd6206b64f517cd340e4f8128807a3c3a#diff-8cc7b2b0d78dd2501610391c086a8516
Fix the broken links in the readme
View the markdown and click the links
**Checklist**
closes #
https://github.com/quintilesims/layer0/issues/599
=> Update contributing and release note links.

api/backend/ecs/resource_manager.go, common/db/job_store/memory.go, setup/module/api/core.tf, setup/module/api/db.tf, setup/module/main.tf
Layer0 v0.10.10 will be a maintenance release as a result of [JIRA issue OCEMCM-4887](https://jiraims.rm.imshealth.com/browse/OCEMCM-4887). It contains updates to use >= v2.0.0 of the AWS terraform module, and enables DynamoDB tables to scale with load.
Successfully run a complete `l0-setup` and confirm that nothing breaks. Confirm that functionality of `l0` has not been broken. Confirm that DynamoDB tables are able to scale under various loads.
=> 4887: Maintenance

common/config/config.go
https://jiraims.rm.imshealth.com/browse/OCEMCM-9485
=> OCEMCM-9485
